[pytest]
pythonpath = .
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = manual disabled results integration scorers_broken utils_broken golden_standard __pycache__
addopts = -m "not slow and not integration"